apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-rbac # moze biti bilo koji
  name: pod-reader
rules:
- apiGroups: [""] # ukazuje na core API grupu
  resources: ["pods"]
  verbs: ["get","watch","list"]
